extends GdUnitTestSuite
## AlignmentTable unit tests (T-115), pinned to `shared/golden/frame_eval.json` (generated by
## `tools/make_golden.py: frame_eval()` from the real Kralupy alignment via `domain/lrs.py: frames()`).
##
## The golden's eight stations are themselves highly irregular — gaps from 3.9 m to 4085 m — exactly the
## non-uniform spacing `bake_stations` produces on a real bake, so building the table straight from these
## real, backend-computed rows exercises binary search over genuine non-uniform spacing without spawning
## a backend. No backend, no network — must stay fast enough for `-a tests/unit`.
##
## Tolerances (task spec): positions to 1e-3 m, quaternion components to 1e-5, angles to 1e-5 rad. cant
## and curvature aren't listed explicitly; they get the same order of tolerance as angles/positions
## respectively since they are float32-vs-float64 comparisons of the same kind.

const _POS_TOL := 1e-3
const _QUAT_TOL := 1e-5
const _ANGLE_TOL := 1e-5
const _CURVATURE_TOL := 1e-5
const _CANT_TOL := 1e-3

var _golden: Dictionary
var _table: AlignmentTable


func before() -> void:
	_golden = GoldenLoader.load_golden("frame_eval")


func before_test() -> void:
	_table = _build_table_from_golden(_golden)


func _build_table_from_golden(golden: Dictionary) -> AlignmentTable:
	var rows: Array = golden.get("rows", [])
	var stations := PackedFloat32Array()
	var positions := PackedVector3Array()
	var rotations := PackedFloat32Array()
	var roll := PackedFloat32Array()
	var pitch := PackedFloat32Array()
	var cant_mm := PackedFloat32Array()
	var curvature := PackedFloat32Array()

	for row: Dictionary in rows:
		stations.append(row["station"])
		var p: Array = row["godot_position"]
		positions.append(Vector3(p[0], p[1], p[2]))
		var q: Array = row["godot_quaternion_xyzw"]
		rotations.append(q[0])
		rotations.append(q[1])
		rotations.append(q[2])
		rotations.append(q[3])
		roll.append(row["roll"])
		pitch.append(row["pitch"])
		cant_mm.append(row["cant_mm"])
		curvature.append(row["curvature"])

	var envelope := IpcEnvelope.new()
	envelope.result = {
		"alignment_id": "kralupy-frame-eval-golden",
		"row_count": stations.size(),
		"station_start": stations[0],
		"station_end": stations[stations.size() - 1],
	}
	envelope.blobs = {
		"station": stations,
		"position": positions,
		"rotation": rotations,
		"roll": roll,
		"pitch": pitch,
		"cant_mm": cant_mm,
		"curvature": curvature,
	}
	return AlignmentTable.from_envelope(envelope)


func test_golden_fixture_loaded() -> void:
	assert_bool(_golden.is_empty()).is_false()
	assert_int((_golden.get("rows", []) as Array).size()).is_greater(0)


func test_alignment_id_and_bounds_come_from_the_envelope_result() -> void:
	var rows: Array = _golden["rows"]
	assert_str(_table.alignment_id()).is_equal("kralupy-frame-eval-golden")
	assert_int(_table.row_count()).is_equal(rows.size())
	# `_build_table_from_golden` round-trips the bound stations through the same PackedFloat32Array the
	# blob itself uses, so the tolerance is float32 ULP-sized at ~18185 m (~2e-3), not float64-exact.
	assert_float(_table.station_start()).is_equal_approx(float(rows[0]["station"]), 1e-2)
	assert_float(_table.station_end()).is_equal_approx(float(rows[rows.size() - 1]["station"]), 1e-2)


func test_sample_reproduces_every_golden_row() -> void:
	for row: Dictionary in _golden["rows"]:
		var station: float = row["station"]
		var sample := _table.sample(station)

		var pos_arr: Array = row["godot_position"]
		var expected_position := Vector3(pos_arr[0], pos_arr[1], pos_arr[2])
		assert_vector(sample.position).append_failure_message(
			"station=%s expected=%s computed=%s" % [station, expected_position, sample.position]
		).is_equal_approx(expected_position, Vector3(_POS_TOL, _POS_TOL, _POS_TOL))

		var quat_arr: Array = row["godot_quaternion_xyzw"]
		assert_float(sample.rotation.x).append_failure_message("station=%s quat.x" % station).is_equal_approx(
			float(quat_arr[0]), _QUAT_TOL
		)
		assert_float(sample.rotation.y).append_failure_message("station=%s quat.y" % station).is_equal_approx(
			float(quat_arr[1]), _QUAT_TOL
		)
		assert_float(sample.rotation.z).append_failure_message("station=%s quat.z" % station).is_equal_approx(
			float(quat_arr[2]), _QUAT_TOL
		)
		assert_float(sample.rotation.w).append_failure_message("station=%s quat.w" % station).is_equal_approx(
			float(quat_arr[3]), _QUAT_TOL
		)

		assert_float(sample.roll).append_failure_message("station=%s roll" % station).is_equal_approx(
			float(row["roll"]), _ANGLE_TOL
		)
		assert_float(sample.pitch).append_failure_message("station=%s pitch" % station).is_equal_approx(
			float(row["pitch"]), _ANGLE_TOL
		)
		assert_float(sample.cant_mm).append_failure_message("station=%s cant_mm" % station).is_equal_approx(
			float(row["cant_mm"]), _CANT_TOL
		)
		assert_float(sample.curvature).append_failure_message("station=%s curvature" % station).is_equal_approx(
			float(row["curvature"]), _CURVATURE_TOL
		)


func test_position_at_matches_sample_position() -> void:
	for row: Dictionary in _golden["rows"]:
		var station: float = row["station"]
		var sample := _table.sample(station)
		var pos := _table.position_at(station)
		assert_vector(pos).is_equal_approx(sample.position, Vector3(1e-6, 1e-6, 1e-6))


func test_index_of_matches_exact_row_stations() -> void:
	# Queries the table's own (float32) stored breakpoints, not the float64 golden value: the wire
	# format only carries stations as float32, and rounding can go either way at storage time — e.g.
	# 53.916823 rounds UP to 53.9168243..., so querying with the float64 golden value directly would sit
	# a hair below the stored breakpoint and land one row early. `index_of` promises "last row with
	# station <= s" against what's actually in the table, not against a value it never saw.
	var stations := _table.stations()
	for i in stations.size():
		var station: float = stations[i]
		assert_int(_table.index_of(station)).append_failure_message("station=%s" % station).is_equal(i)


func test_index_of_between_rows_returns_the_lower_row() -> void:
	var rows: Array = _golden["rows"]
	for i in rows.size() - 1:
		var s0: float = rows[i]["station"]
		var s1: float = rows[i + 1]["station"]
		var mid := (s0 + s1) * 0.5
		assert_int(_table.index_of(mid)).append_failure_message(
			"midpoint between station %s and %s" % [s0, s1]
		).is_equal(i)


func test_index_of_before_first_row_is_minus_one() -> void:
	var first: float = _golden["rows"][0]["station"]
	assert_int(_table.index_of(first - 1.0)).is_equal(-1)


func test_index_of_at_and_beyond_last_row_is_the_last_index() -> void:
	var rows: Array = _golden["rows"]
	var last: float = rows[rows.size() - 1]["station"]
	assert_int(_table.index_of(last)).is_equal(rows.size() - 1)
	assert_int(_table.index_of(last + 10000.0)).is_equal(rows.size() - 1)


func test_sample_clamps_before_start_and_after_end() -> void:
	var rows: Array = _golden["rows"]
	var first: Dictionary = rows[0]
	var last: Dictionary = rows[rows.size() - 1]

	var before_sample := _table.sample(float(first["station"]) - 500.0)
	var first_pos: Array = first["godot_position"]
	assert_vector(before_sample.position).is_equal_approx(
		Vector3(first_pos[0], first_pos[1], first_pos[2]), Vector3(_POS_TOL, _POS_TOL, _POS_TOL)
	)

	var after_sample := _table.sample(float(last["station"]) + 5000.0)
	var last_pos: Array = last["godot_position"]
	assert_vector(after_sample.position).is_equal_approx(
		Vector3(last_pos[0], last_pos[1], last_pos[2]), Vector3(_POS_TOL, _POS_TOL, _POS_TOL)
	)


func test_sample_between_rows_is_bounded_by_neighbours_and_continuous() -> void:
	var rows: Array = _golden["rows"]
	var i := 3  # station 1000.0 -> 5038.0: a wide, curved span with no golden row in between
	var s0: float = rows[i]["station"]
	var s1: float = rows[i + 1]["station"]
	var mid := (s0 + s1) * 0.5

	var lo := _table.sample(s0)
	var hi := _table.sample(s1)
	var mid_sample := _table.sample(mid)

	var lo_x := lo.position.x
	var hi_x := hi.position.x
	assert_float(mid_sample.position.x).append_failure_message(
		"x: lo=%s hi=%s mid=%s" % [lo_x, hi_x, mid_sample.position.x]
	).is_between(minf(lo_x, hi_x) - 1e-3, maxf(lo_x, hi_x) + 1e-3)

	var lo_y := lo.position.y
	var hi_y := hi.position.y
	assert_float(mid_sample.position.y).append_failure_message(
		"y: lo=%s hi=%s mid=%s" % [lo_y, hi_y, mid_sample.position.y]
	).is_between(minf(lo_y, hi_y) - 1e-3, maxf(lo_y, hi_y) + 1e-3)

	var lo_z := lo.position.z
	var hi_z := hi.position.z
	assert_float(mid_sample.position.z).append_failure_message(
		"z: lo=%s hi=%s mid=%s" % [lo_z, hi_z, mid_sample.position.z]
	).is_between(minf(lo_z, hi_z) - 1e-3, maxf(lo_z, hi_z) + 1e-3)

	assert_float(mid_sample.curvature).append_failure_message(
		"curvature: lo=%s hi=%s mid=%s" % [lo.curvature, hi.curvature, mid_sample.curvature]
	).is_between(minf(lo.curvature, hi.curvature) - 1e-6, maxf(lo.curvature, hi.curvature) + 1e-6)

	# Continuity: nudging the query station by a tiny step must not jump the result. Position changes
	# roughly linearly at ~0.94 m per metre of station over this span, so a 1e-4 m step moves it by
	# under 0.1 mm — the 1e-3 m tolerance below leaves a comfortable margin either side.
	var h := 1e-4
	var just_below := _table.sample(mid - h)
	var just_above := _table.sample(mid + h)
	assert_vector(just_below.position).append_failure_message("continuity below mid=%s" % mid).is_equal_approx(
		mid_sample.position, Vector3(1e-3, 1e-3, 1e-3)
	)
	assert_vector(just_above.position).append_failure_message("continuity above mid=%s" % mid).is_equal_approx(
		mid_sample.position, Vector3(1e-3, 1e-3, 1e-3)
	)


func test_slerp_gives_a_unit_quaternion_and_differs_from_the_normalised_linear_blend() -> void:
	var rows: Array = _golden["rows"]
	var i := 6  # 16300.0 -> 18184.971666: a ~41 degree heading swing between adjacent golden rows
	var q0_arr: Array = rows[i]["godot_quaternion_xyzw"]
	var q1_arr: Array = rows[i + 1]["godot_quaternion_xyzw"]
	var q0 := Quaternion(q0_arr[0], q0_arr[1], q0_arr[2], q0_arr[3])
	var q1 := Quaternion(q1_arr[0], q1_arr[1], q1_arr[2], q1_arr[3])

	var s0: float = rows[i]["station"]
	var s1: float = rows[i + 1]["station"]
	# Deliberately not the midpoint: slerp(a, b, 0.5) and normalize(lerp(a, b, 0.5)) are identical by
	# construction (both land on the chord's midpoint, which is also the great-circle arc's midpoint) —
	# t=0.25 is where the two curves actually separate.
	var t := 0.25
	var query := lerpf(s0, s1, t)
	var sampled := _table.sample(query).rotation

	assert_float(sampled.length()).append_failure_message(
		"slerp result should stay a unit quaternion, got length=%s" % sampled.length()
	).is_equal_approx(1.0, 1e-4)

	var linear := Quaternion(
		lerpf(q0.x, q1.x, t), lerpf(q0.y, q1.y, t), lerpf(q0.z, q1.z, t), lerpf(q0.w, q1.w, t)
	).normalized()

	var max_component_diff := maxf(
		maxf(absf(sampled.x - linear.x), absf(sampled.y - linear.y)),
		maxf(absf(sampled.z - linear.z), absf(sampled.w - linear.w))
	)
	assert_float(max_component_diff).append_failure_message(
		"slerp result matched the normalised linear blend too closely (diff=%s) — looks like lerp, not slerp"
		% max_component_diff
	).is_greater(1e-4)
