extends GdUnitTestSuite
## RunTable unit tests (T-115), pinned to `shared/golden/run_table.json` (generated by
## `tools/make_golden.py: run_table()` from the Kralupy `.coypu` run via `domain/kinematics.py:
## bake_run_table`).
##
## The golden only carries a sparse spread of the real 23182-row table (station/speed/accel at 20
## representative indices, including the row nearest the first stop's dwell). `station_at`/`speed_at`/
## `accel_at` are O(1) — `i = t / dt` — and every golden `t` was itself computed as `index * dt` (or, for
## the last row, set to `duration`, which is `dt * (row_count - 1)` to double precision), so recomputing
## `t / dt` always lands within a few ULPs of that same integer index — verified to be bit-exact (frac ==
## 0.0) for every golden sample below. `_build_table_from_golden` exploits that: every row the golden
## doesn't carry is filled with `_SENTINEL`, a value wildly outside any plausible station/speed/accel
## range, rather than a plausible placeholder — so if the lookup ever leaned on a neighbour by more than a
## hair the assertions below fail loudly with an out-of-tolerance value. (An earlier version of this file
## used NAN for that role; `GdUnitFloatAssertImpl.is_between` — what `is_equal_approx` delegates to —
## checks `current < from or current > to`, both of which are false for NaN, so it silently reports
## success instead of failing. A NaN "poisons" a `lerpf` unconditionally, at any weight including exactly
## 0.0, which made every assertion here pass without checking anything. A large finite sentinel avoids
## both problems.) No backend, no network — must stay fast enough for `-a tests/unit`.

const _STATION_TOL := 1e-3
const _SPEED_TOL := 1e-3
const _ACCEL_TOL := 1e-3
const _SENTINEL := 1.0e6

var _golden: Dictionary
var _table: RunTable


func before() -> void:
	_golden = GoldenLoader.load_golden("run_table")


func before_test() -> void:
	_table = _build_table_from_golden(_golden)


func _build_table_from_golden(golden: Dictionary) -> RunTable:
	var row_count: int = golden["row_count"]
	var station := PackedFloat32Array()
	var speed := PackedFloat32Array()
	var accel := PackedFloat32Array()
	station.resize(row_count)
	speed.resize(row_count)
	accel.resize(row_count)
	for i in row_count:
		station[i] = _SENTINEL
		speed[i] = _SENTINEL
		accel[i] = _SENTINEL

	for entry: Dictionary in golden["samples"]:
		var i: int = entry["index"]
		station[i] = entry["station"]
		speed[i] = entry["speed"]
		accel[i] = entry["accel"]

	var envelope := IpcEnvelope.new()
	envelope.result = {
		"run_id": "kralupy-run-golden",
		"dt": golden["dt"],
		"row_count": row_count,
		"duration_s": golden["duration"],
		"direction": 1,
		"stops": [],
	}
	envelope.blobs = {"station": station, "speed": speed, "accel": accel}
	return RunTable.from_envelope(envelope)


func test_golden_fixture_loaded() -> void:
	assert_bool(_golden.is_empty()).is_false()
	assert_int((_golden.get("samples", []) as Array).size()).is_greater(0)


func test_basic_accessors_come_from_the_envelope_result() -> void:
	assert_str(_table.run_id()).is_equal("kralupy-run-golden")
	assert_float(_table.dt()).is_equal_approx(float(_golden["dt"]), 1e-9)
	assert_float(_table.duration()).is_equal_approx(float(_golden["duration"]), 1e-9)
	assert_int(_table.row_count()).is_equal(int(_golden["row_count"]))
	assert_int(_table.direction()).is_equal(1)
	assert_bool(_table.has_forces()).is_false()
	assert_float(_table.traction_at(0.0)).is_equal(0.0)


func test_station_and_speed_reproduce_every_golden_sample() -> void:
	for entry: Dictionary in _golden["samples"]:
		var t: float = entry["t"]
		var got_station := _table.station_at(t)
		var got_speed := _table.speed_at(t)

		assert_float(got_station).append_failure_message(
			"index=%s t=%s expected_station=%s got=%s" % [entry["index"], t, entry["station"], got_station]
		).is_equal_approx(float(entry["station"]), _STATION_TOL)
		assert_float(got_speed).append_failure_message(
			"index=%s t=%s expected_speed=%s got=%s" % [entry["index"], t, entry["speed"], got_speed]
		).is_equal_approx(float(entry["speed"]), _SPEED_TOL)


func test_accel_reproduces_every_golden_sample() -> void:
	for entry: Dictionary in _golden["samples"]:
		var t: float = entry["t"]
		assert_float(_table.accel_at(t)).append_failure_message(
			"index=%s t=%s" % [entry["index"], t]
		).is_equal_approx(float(entry["accel"]), _ACCEL_TOL)


func test_in_dwell_sample_reproduces_golden_speed_and_station() -> void:
	var dwell_index: int = _golden["dwell_index"]
	var entry: Dictionary = {}
	for e: Dictionary in _golden["samples"]:
		if int(e["index"]) == dwell_index:
			entry = e
			break
	assert_bool(entry.is_empty()).append_failure_message(
		"dwell_index %s not present in golden samples" % dwell_index
	).is_false()
	if entry.is_empty():
		return

	var got_station := _table.station_at(entry["t"])
	var got_speed := _table.speed_at(entry["t"])
	assert_float(got_speed).append_failure_message("in-dwell speed should be near zero, got %s" % got_speed).is_less(0.1)
	assert_float(got_station).is_equal_approx(float(entry["station"]), _STATION_TOL)
	assert_float(got_speed).is_equal_approx(float(entry["speed"]), _SPEED_TOL)


func test_station_at_is_clamped_and_finite_at_boundaries() -> void:
	var duration: float = _golden["duration"]
	var samples: Array = _golden["samples"]
	var first_station: float = samples[0]["station"]
	var last_station: float = samples[samples.size() - 1]["station"]

	var before_start := _table.station_at(-10.0)
	assert_bool(is_finite(before_start)).is_true()
	assert_float(before_start).is_equal_approx(first_station, _STATION_TOL)

	var at_duration := _table.station_at(duration)
	assert_bool(is_finite(at_duration)).is_true()
	assert_float(at_duration).is_equal_approx(last_station, _STATION_TOL)

	var past_duration := _table.station_at(duration * 10.0)
	assert_bool(is_finite(past_duration)).is_true()
	assert_float(past_duration).is_equal_approx(at_duration, 1e-6)


## Five hand-built, fully-real rows (no NAN placeholders) modelling a short dwell: flat station and zero
## speed for two consecutive rows, then departure. Proves the O(1) lerp itself introduces no spike or
## special-cased jump, independent of the golden fixture's sparse coverage above.
func test_dwell_interpolation_has_no_spike() -> void:
	var dt := 0.05
	var envelope := IpcEnvelope.new()
	envelope.result = {
		"run_id": "dwell-smoke-test",
		"dt": dt,
		"row_count": 5,
		"duration_s": dt * 4.0,
		"direction": 1,
		"stops": [],
	}
	envelope.blobs = {
		"station": PackedFloat32Array([100.0, 100.0, 100.0, 100.5, 101.5]),
		"speed": PackedFloat32Array([2.0, 0.0, 0.0, 1.0, 2.0]),
		"accel": PackedFloat32Array([-4.0, 0.0, 0.0, 2.0, 2.0]),
	}
	var table := RunTable.from_envelope(envelope)

	# Mid-dwell (row 1 to row 2): station stays flat and speed stays at zero everywhere in the interval.
	for frac in [0.0, 0.25, 0.5, 0.75, 1.0]:
		var t: float = dt * (1.0 + frac)
		assert_float(table.station_at(t)).append_failure_message("t=%s" % t).is_equal_approx(100.0, 1e-4)
		assert_float(table.speed_at(t)).append_failure_message("t=%s" % t).is_equal_approx(0.0, 1e-4)

	# Crossing into departure (row 2 to row 3): speed rises smoothly, never overshooting either endpoint.
	var mid_departure := table.speed_at(dt * 2.5)
	assert_float(mid_departure).is_between(0.0, 1.0)


func test_has_forces_true_when_force_blobs_are_present() -> void:
	var envelope := IpcEnvelope.new()
	envelope.result = {
		"run_id": "force-smoke-test",
		"dt": 0.05,
		"row_count": 3,
		"duration_s": 0.1,
		"direction": 1,
		"stops": [],
	}
	envelope.blobs = {
		"station": PackedFloat32Array([0.0, 1.0, 2.0]),
		"speed": PackedFloat32Array([0.0, 1.0, 2.0]),
		"accel": PackedFloat32Array([1.0, 1.0, 1.0]),
		"f_traction": PackedFloat32Array([10.0, 20.0, 30.0]),
	}
	var table := RunTable.from_envelope(envelope)

	assert_bool(table.has_forces()).is_true()
	assert_float(table.traction_at(0.05)).is_equal_approx(20.0, 1e-3)
