"""Render `docs/protocol/ipc.md` from `protocol/messages.py` (ADR 0003).

Run from backend/: `uv run python ../tools/gen_protocol_docs.py`. `--check` renders to memory, diffs against
the file on disk and exits 1 on mismatch instead of writing — this is the CI freshness gate. Never hand-edit
`docs/protocol/ipc.md`; `protocol/messages.py` (the `METHODS` registry) is the single source of truth.
"""

from __future__ import annotations

import argparse
import difflib
import sys
import types
import typing
from pathlib import Path
from typing import Any

import msgspec

from coypu_builder import PROTOCOL_VERSION
from coypu_builder.protocol.messages import METHODS, ErrorCode, MethodSpec

ROOT = Path(__file__).resolve().parents[1]
DOCS_PATH = ROOT / "docs" / "protocol" / "ipc.md"

_GENERATED_BANNER = (
    "<!-- generated by tools/gen_protocol_docs.py from backend/src/coypu_builder/protocol/messages.py "
    "— do not hand-edit -->"
)

_ENVELOPE_SECTION = """\
## Envelope and framing

One localhost WebSocket connection carries request/response messages (matched by `id`) plus server-push
events. Every frame is:

```
[u32 LE header_len][UTF-8 JSON header][blob 0][blob 1]...
```

The JSON header is the `Envelope`: `v` (protocol version), `id`, `type` (`req` | `res` | `evt` | `err`),
`method`, one of `params` / `result` / `error`, and a `blobs` list of
`{name, dtype, shape, offset, length}` describing spans of the binary tail that follows the header
(little-endian, C-order). Godot decodes a span with `PackedByteArray.slice(...).to_float32_array()` etc.;
Python with `np.frombuffer`.

The client spawns `coypu-builder-backend serve --port 0 --token <random>`, reads `{"port": N}` from stdout,
sends `session.hello`, then heartbeats with `session.ping` every 2 s and restarts the backend on connection
loss. `--backend-url` attaches to an externally started backend for debugging.
"""

_BLOB_SECTION = """\
## Blob encoding

A method result may carry zero or more named blobs instead of putting bulk numeric data in the JSON
`result`. Each blob is one contiguous span of the frame's binary tail: little-endian, C-order, described by
a `dtype` (numpy dtype string, e.g. `<f4`, `<i4`) and a documentation `shape` such as `(n,)` or `(n, 3)`,
where `n` is the row count for that method call. Bulk static assets (terrain height tiles, ortho images) are
written to a session cache directory and referenced by path in the JSON `result` instead of riding a blob.
"""


def _format_type(tp: Any) -> str:
    if tp is type(None):
        return "None"
    if tp is typing.Any:
        return "Any"
    origin = typing.get_origin(tp)
    if origin is types.UnionType or origin is typing.Union:
        return " | ".join(_format_type(arg) for arg in typing.get_args(tp))
    if origin is tuple:
        args = typing.get_args(tp)
        if len(args) == 2 and args[1] is Ellipsis:
            return f"tuple[{_format_type(args[0])}, ...]"
        return f"tuple[{', '.join(_format_type(arg) for arg in args)}]"
    if origin is not None:
        args = typing.get_args(tp)
        name = getattr(origin, "__name__", str(origin))
        return f"{name}[{', '.join(_format_type(arg) for arg in args)}]" if args else name
    return getattr(tp, "__name__", str(tp))


def _format_default(field: msgspec.structs.FieldInfo) -> str:
    if field.default is not msgspec.NODEFAULT:
        return f"`{field.default!r}`"
    if field.default_factory is not msgspec.NODEFAULT:
        return f"`{field.default_factory()!r}`"
    return "required"


def _render_struct_table(struct_type: type) -> list[str]:
    lines = ["| Field | Type | Default |", "|---|---|---|"]
    for f in msgspec.structs.fields(struct_type):
        lines.append(f"| `{f.name}` | `{_format_type(f.type)}` | {_format_default(f)} |")
    return lines


def _render_method(spec: MethodSpec) -> list[str]:
    lines = [f"### `{spec.name}`", "", spec.summary, "", "**Params**", ""]
    lines.extend(_render_struct_table(spec.params) if spec.params is not None else ["None."])
    lines.extend(["", "**Result**", ""])
    lines.extend(_render_struct_table(spec.result) if spec.result is not None else ["None."])
    lines.append("")
    if spec.blobs:
        lines.extend(["**Blobs**", "", "| Name | dtype | Shape | Description |", "|---|---|---|---|"])
        lines.extend(f"| `{b.name}` | `{b.dtype}` | `{b.shape}` | {b.description} |" for b in spec.blobs)
        lines.append("")
    errors = ", ".join(f"`{e.value}`" for e in spec.errors) if spec.errors else "none"
    lines.extend([f"**Errors**: {errors}", ""])
    return lines


def render() -> str:
    lines: list[str] = [
        _GENERATED_BANNER,
        "",
        "# COYPU Builder IPC protocol",
        "",
        f"Localhost WebSocket IPC, protocol version `{PROTOCOL_VERSION}` (ADR 0003). "
        "`backend/src/coypu_builder/protocol/messages.py` (the `METHODS` registry) is the single source of "
        "truth; regenerate this file with `uv run python ../tools/gen_protocol_docs.py` from `backend/`.",
        "",
        _ENVELOPE_SECTION,
        _BLOB_SECTION,
        "## Error codes",
        "",
        "| Name | Value |",
        "|---|---|",
    ]
    lines.extend(f"| `{code.name}` | `{code.value}` |" for code in ErrorCode)
    lines.extend(["", "## Methods", ""])
    for spec in METHODS:
        lines.extend(_render_method(spec))
    text = "\n".join(lines)
    while text.endswith("\n\n"):
        text = text[:-1]
    return text if text.endswith("\n") else text + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="diff against the file on disk instead of writing"
    )
    args = parser.parse_args(argv)

    doc = render()
    if args.check:
        current = DOCS_PATH.read_text(encoding="utf-8") if DOCS_PATH.exists() else ""
        if current == doc:
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            doc.splitlines(keepends=True),
            fromfile=str(DOCS_PATH),
            tofile="<generated>",
        )
        sys.stdout.writelines(diff)
        return 1

    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.write_text(doc, encoding="utf-8", newline="\n")
    print(f"wrote {DOCS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
